### ISSUE TITLE
Lock Screen Theme

### ISSUE THREAD

**Issue by azubieta** [nomad-shell/nomad-plasma-look-and-feel#2]
Create a lock screen view similar to the SDDM greeter screen.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/WuWHvxm.png)

The lock screen retains the panel at the top with the clock like the SDDM theme. At the middle there's the clock in 24H format and the date below it. The font size of the clock is 80 pts and the date is 20 pts and their weight is Thin/Light.

![](http://i.imgur.com/ibBzD6q.png)

To unlock the user has to click on "Unlock" for the password field to show, enter the password and clikc "Unlock" again to go back to the desktop.

**Comment by azubieta** [comment]
There will be no option to switch user ?

**Comment by UriHerrera** [comment]
No, switching user should be done at login.

**Comment by azubieta** [comment]
Already commit a version, there is only missing the button color. I think that we must set it using the system theme colors in case of similar colors will be used elsewhere. What do you say ?

**Comment by UriHerrera** [comment]
Yep like it is right now is perfect.
