### ISSUE TITLE
Shutdown screen

### ISSUE THREAD

**Issue by azubieta** [nomad-shell/nomad-plasma-look-and-feel#3]
Create a shutdown screen similar to the SDDM greeter theme.

**Comment by UriHerrera** [comment]
For the shutdown screen the only changes would be to use the avatar from SDDM theme and change the color of the overlay to #f5f5f5 and the text to #212121.

**Comment by azubieta** [comment]
@UriHerrera this is the default logout screen that I have in my system, are we going to keep it just like it is, but only with the changes that you pointed out?

Also the user avatar if none is set is taken from the system default, there is were we must change it, so it will be the same in the whole system.

![screenshot_logout](https://cloud.githubusercontent.com/assets/1138094/20985071/d9b9f2e4-bc90-11e6-9f38-0fa34cfb38d2.png)

**Comment by UriHerrera** [comment]
Yes, I think the design is pretty nice and we'd only need these changes to make it fit with the rest of the theming.

Is the avatar an icon? if it is I can add it to the Plasma theme or the icon theme then.

**Comment by azubieta** [comment]
The fall-back icon is: "user-identity", you can change it on the icon theme so it will be replaced there too.

**Comment by UriHerrera** [comment]
I'll add the icon to the icon theme.
