### ISSUE TITLE
Welcome screen Theme

### ISSUE THREAD

**Issue by UriHerrera** [nomad-shell/nomad-plasma-look-and-feel#4]
For the welcome screen I think something that indicates that the desktop is launching would be nice.  The background is #f5f5f5 and the color of the progress bar is #00acc1 for the border and #26c6da for the fill.

[I made a GIF of the animation](http://i.imgur.com/j8iYM2o.gifv). [Here are the logo and the rocket icon](https://drive.google.com/open?id=0B7tTOld4xNXCcDdwOC1nRFpHNkk)

**Comment by azubieta** [comment]
Done, please check it.
@UriHerrera  I made it in way that each step of the animation match with an stage of the loading process. It's OK in that way or I just make two animations one at the beginning and other at the end?
